#!/bin/bash
spacer="----------------------------------------------------------------"
 
echo -e "$spacer\nEnter the directory path you would like to backup\n$spacer"
read location
cd $location || exit 1

echo -e "$spacer\nEnter the directory where the backup should go\n$spacer"
read backlog
cd $backlog || exit 1
cd $location

echo -e "$spacer\nEnter Backup Codename\n$spacer"
read CODE

backupCount=$(find . -type f | wc -l)
FILECHECK=$location/$code.7z

7z a -mhe $backlog/$CODE.7z

#Issues
#No Password Suupport

#To Do
#Create password Support and give an option to add a password
#Create A confirmation Notice
